# Generated by Django 3.2.4 on 2021-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publishing_date', 'id']},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('software', 'yazilim'), ('product', 'urun'), ('game', 'oyun'), ('book', 'kitap'), ('movie', 'film')], default='software', max_length=10),
        ),
    ]
